### PR TITLE
requestFile Implementation

### PR DESCRIPTION
**Pull request by dghelm**
Initial implementation for requestFile. No sanity checks for large files or anything else.

Addresses issue #129

### CODE REVIEW

**Review by mrcnski — APPROVED** [review]

**Comment by kwypchlo** [comment]
I would wonder whether it should be called `readFile` or `getFileContent` instead. Probably `getFileContent` is a better idea and would sound more cohesive with `getMetadata`.

**Review by interstella-5555 — COMMENTED** [review]
I would wonder whether it should be called `readFile` or `getFileContent` instead. Probably `getFileContent` is a better idea and would sound more cohesive with `getMetadata`. 

edit: or maybe `getContent` but I would argue it's too vague and generic

**Comment by dghelm** [comment]
I agree that `Request` is a little clunky here. My concern with `getFileContent` is that `getFile` is using SkyDB (at least with its initial SDK), so I think that gets confusing, but I think that's just an issue with the SkyDB method name more than anything in the Download methods.

I think with the current naming structure, `readFile` or `readSkylink` make sense, as well as `getSkylinkContents` since there is a `getSkylinkUrl`. That said (and this is obviously not a conversation for a pull request), there may need to be a standardized naming structure (even if just aliases for existing methods) that allow the developer to always know what data space they're dealing with (skylinks, metadata, files, db entries, etc).

**Comment by mrcnski** [comment]
> That said (and this is obviously not a conversation for a pull request), there may need to be a standardized naming structure (even if just aliases for existing methods) that allow the developer to always know what data space they're dealing with (skylinks, metadata, files, db entries, etc).

We started doing this with SkyDB and the Registry (e.g. `client.db.getJSON` and `client.registry.getEntry`)

With this in mind I think `getFileContent` would be a good name, especially since we ended up removing `getFile` in the final version of the SkyDB API.

**Comment by MSevey** [comment]
Comments, please add comments and descriptions to the new functions :-)

**Comment by dghelm** [comment]
Okay I think it should be good to go.

**Review by mrcnski — DISMISSED** [review]

**Review by interstella-5555 — DISMISSED** [review]
I am going to approve it but we should take a look at our SDK methods. If we would want to be consistent with the naming, we already have `getSkylinkUrl` so this new method should probably be `getSkylinkContent`. Otherwise `getSkylinkUrl` should be called `getFileUrl`. I will leave it to you @dhelma to determine how is the SDK methods naming affecting the general developer sdk usability and methods discoverability.

**Comment by dghelm** [comment]
> I am going to approve it but we should take a look at our SDK methods. If we would want to be consistent with the naming, we already have `getSkylinkUrl` so this new method should probably be `getSkylinkContent`. Otherwise `getSkylinkUrl` should be called `getFileUrl`. I will leave it to you @dhelma to determine how is the SDK methods naming affecting the general developer sdk usability and methods discoverability.

I think File here works, since it doesn't make much sense to use it for Directories. I agree we're going to need a large reconsideration of SDK method names, but, as I understand it from a Discord conversation, we're going to implement that once major features have been shipped so we can take a more complete view at it.

**Review by mrcnski — DISMISSED** [review]

**Review by mrcnski — APPROVED** [review]

**Review by interstella-5555 — APPROVED** [review]

**Pull request merged**
